# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lqk7Ej8RZmw3GOpil7qvsWKlvMxiRQ2U
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# ── CONFIG ──────────────────────────────────────────
st.set_page_config(
    page_title="EatSistent Dashboard",
    page_icon="🥗",
    layout="wide"
)

# ── LOAD DATA ────────────────────────────────────────
@st.cache_data
def load_data():
    user = pd.read_csv('user_dataset/user_profile_labeled.csv')
    tkpi = pd.read_csv('nutrition_dataset/tkpi_clean_labeled.csv')
    return user, tkpi

df_user, df_tkpi = load_data()

# ── HEADER ───────────────────────────────────────────
st.title("🥗 EatSistent — Dashboard Analisis Nutrisi")
st.caption("Capstone Project CC26-PSU274 | Healthy Lives & Well-being")
st.divider()

# ── TABS ─────────────────────────────────────────────
tab1, tab2 = st.tabs([
    "📊 Pertanyaan 1 — Profil Nutrisi User",
    "🥦 Pertanyaan 2 — Distribusi Kelas Makanan"
])

# ════════════════════════════════════════════════════
# TAB 1 — PROFIL NUTRISI USER
# ════════════════════════════════════════════════════
with tab1:
    st.subheader("Kebutuhan Nutrisi Harian Berdasarkan Profil User")

    # Sidebar filter khusus tab 1
    with st.sidebar:
        st.header("Filter Tab 1")
        gender = st.multiselect(
            "Jenis Kelamin",
            options=df_user['jenis_kelamin'].unique(),
            default=df_user['jenis_kelamin'].unique()
        )
        target = st.multiselect(
            "Target User",
            options=df_user['target_user'].unique(),
            default=df_user['target_user'].unique()
        )

    df_filtered = df_user[
        (df_user['jenis_kelamin'].isin(gender)) &
        (df_user['target_user'].isin(target))
    ]

    # Metric cards
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Total User", len(df_filtered))
    col2.metric("Rata-rata Kalori (kkal)", round(df_filtered['akg_energi_kkal'].mean()))
    col3.metric("Rata-rata Protein (g)", round(df_filtered['akg_protein_g'].mean()))
    col4.metric("Rata-rata BMI", round(df_filtered['bmi'].mean(), 1))

    st.divider()

    col_a, col_b = st.columns(2)

    with col_a:
        # Chart 1: Distribusi BMI
        fig1 = px.histogram(
            df_filtered, x='bmi',
            color='jenis_kelamin',
            nbins=30,
            title='Distribusi BMI per Jenis Kelamin',
            labels={'bmi': 'BMI', 'jenis_kelamin': 'Jenis Kelamin'}
        )
        st.plotly_chart(fig1, use_container_width=True)

    with col_b:
        # Chart 2: Rata-rata kalori per kelompok usia & gender
        df_akg_group = df_filtered.groupby(
            ['kelompok_usia', 'jenis_kelamin']
        )['akg_energi_kkal'].mean().reset_index()

        fig2 = px.bar(
            df_akg_group,
            x='kelompok_usia', y='akg_energi_kkal',
            color='jenis_kelamin', barmode='group',
            title='Rata-rata Kebutuhan Kalori per Kelompok Usia',
            labels={
                'kelompok_usia': 'Kelompok Usia',
                'akg_energi_kkal': 'Kalori (kkal)',
                'jenis_kelamin': 'Jenis Kelamin'
            }
        )
        st.plotly_chart(fig2, use_container_width=True)

    # Chart 3: Distribusi target user
    fig3 = px.pie(
        df_filtered,
        names='target_user',
        title='Distribusi Target Kebugaran User',
        hole=0.4
    )
    st.plotly_chart(fig3, use_container_width=True)


# ════════════════════════════════════════════════════
# TAB 2 — DISTRIBUSI KELAS MAKANAN TKPI
# ════════════════════════════════════════════════════
with tab2:
    st.subheader("Distribusi Kelas Rekomendasi Makanan TKPI 2017")

    # Filter kategori
    kategori_list = df_tkpi['kategori'].unique().tolist()
    kat_selected = st.multiselect(
        "Filter Kategori Makanan",
        options=kategori_list,
        default=kategori_list
    )

    df_tkpi_f = df_tkpi[df_tkpi['kategori'].isin(kat_selected)]

    # Metric cards
    col1, col2, col3 = st.columns(3)
    col1.metric("Total Bahan Makanan", len(df_tkpi_f))
    col2.metric("Rata-rata Kalori (per 100g)", round(df_tkpi_f['energi_kkal'].mean()))
    col3.metric("Rata-rata Protein (per 100g)", round(df_tkpi_f['protein_g'].mean(), 1))

    st.divider()

    col_a, col_b = st.columns(2)

    with col_a:
        # Chart 1: Jumlah item per kelas
        kelas_count = df_tkpi_f['label_kelas'].value_counts().reset_index()
        kelas_count.columns = ['label_kelas', 'jumlah']
        fig4 = px.bar(
            kelas_count, x='label_kelas', y='jumlah',
            color='label_kelas',
            title='Jumlah Item per Kelas Rekomendasi',
            labels={'label_kelas': 'Kelas', 'jumlah': 'Jumlah Bahan'},
            text='jumlah'
        )
        fig4.update_traces(textposition='outside')
        st.plotly_chart(fig4, use_container_width=True)

    with col_b:
        # Chart 2: Rata-rata makronutrien per kelas
        nutrisi = ['energi_kkal', 'protein_g', 'lemak_g', 'karbohidrat_g']
        df_kelas = df_tkpi_f.groupby('label_kelas')[nutrisi].mean().reset_index()
        df_melt = df_kelas.melt(
            id_vars='label_kelas',
            var_name='nutrisi', value_name='rata_rata'
        )
        fig5 = px.bar(
            df_melt, x='nutrisi', y='rata_rata',
            color='label_kelas', barmode='group',
            title='Rata-rata Makronutrien per Kelas (per 100g)',
            labels={'nutrisi': 'Nutrisi', 'rata_rata': 'Rata-rata', 'label_kelas': 'Kelas'}
        )
        st.plotly_chart(fig5, use_container_width=True)

    # Chart 3: Distribusi kelas per kategori (top 6)
    top6 = df_tkpi_f['kategori'].value_counts().head(6).index
    df_top6 = df_tkpi_f[df_tkpi_f['kategori'].isin(top6)]
    fig6 = px.histogram(
        df_top6, x='kategori',
        color='label_kelas', barmode='stack',
        title='Distribusi Kelas per Kategori Makanan (Top 6)',
        labels={'kategori': 'Kategori', 'label_kelas': 'Kelas'}
    )
    st.plotly_chart(fig6, use_container_width=True)